spring:
  data:
    mongodb:
#      authentication-database: dbAdmin
      username:
      password: 
      database: userdb
      port: 27017
      host: localhost
  application:
    name: user-service
server:
  port: 8080



